[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "atlassian-dashboard-backend"

[services.source]
repo = "your-github-username/atlassian-dashboard-backend"
rootDirectory = "/"

[services.variables]
PORT = "8000"
PYTHONPATH = "/app"

[[services.domains]]
# Railway will auto-assign a domain